path: /content/drive/MyDrive/Colab Notebooks/final dataset  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: male
  1: female